//! Golden regression tests pinning the meaning of published, sense-numbered keys.
//!
//! These lock in the public contract that the assignment lockfiles exist to
//! protect: a key like `lie2` or `die2` must keep producing the same inflection
//! across releases. If a data refresh ever renumbers a homograph, one of these
//! fails loudly instead of silently shipping a swapped meaning.

use english::{count, Degree, English, Form, Number, Person, Tense};

fn past_finite(word: &str) -> String {
    English::verb(
        word,
        &Person::Third,
        &Number::Singular,
        &Tense::Past,
        &Form::Finite,
    )
}

#[test]
fn verb_lie_homographs_are_pinned() {
    // Both homograph senses stay distinct and pinned. The bare-vs-`2` assignment is
    // driven by the (stable) senseid ordering: "lie" (tell an untruth) -> lied ;
    // "lie2" (recline) -> lay.
    assert_eq!(past_finite("lie"), "lied");
    assert_eq!(past_finite("lie2"), "lay");
}

#[test]
fn noun_die_homograph_is_pinned() {
    assert_eq!(English::noun("die2", &Number::Plural), "dice");
}

#[test]
fn adjective_bad_homographs_are_pinned() {
    // Both senses stay distinct: "bad2" (standard) -> worse/worst ; "bad3" (slang)
    // -> badder/baddest. Ordered by the senseid anchor, not the form spelling.
    assert_eq!(English::adj("bad2", &Degree::Comparative), "worse");
    assert_eq!(English::adj("bad2", &Degree::Superlative), "worst");
    assert_eq!(English::adj("bad3", &Degree::Comparative), "badder");
    assert_eq!(English::adj("bad3", &Degree::Superlative), "baddest");
}

#[test]
fn trailing_digits_strip_only_for_real_table_keys() {
    // A trailing-digit run is a sense suffix ONLY when it resolves to a table key.
    // Known suffixed keys strip and resolve; their bare form is the stripped lemma.
    assert_eq!(English::noun("die2", &Number::Plural), "dice");
    assert_eq!(English::noun("die2", &Number::Singular), "die");
    assert_eq!(English::adj("good2", &Degree::Superlative), "best");

    // Digit-bearing words that are NOT table keys are opaque — never corrupted into
    // a digit-stripped stem (this is the strip_trailing_number bug fix).
    assert_eq!(English::noun("mp3", &Number::Plural), "mp3s");
    assert_eq!(English::noun("F16", &Number::Plural), "F16s");
    assert_eq!(English::noun("co2", &Number::Plural), "co2s");
    assert_eq!(English::noun("i7", &Number::Singular), "i7");
    assert_eq!(past_finite("mp3"), "mp3ed");

    // count() ergonomic helper must not mangle a digit-bearing noun.
    assert_eq!(count("F16", 3), "F16s");

    // A numbered key for a REGULAR lemma is never generated by the library, so it is
    // treated opaquely rather than stripped to the bare lemma.
    assert_eq!(English::noun("cat2", &Number::Plural), "cat2s");
}
